export const routeNames = {
    main: '/',
    captcha: '/anti-captcha',
    groups: '/groups',
    group: '/group',
    monitoring: '/monitoring',
    settings: '/settings',
    versions: '/versions',
    projects: '/projects',
    project: '/project-page',
    networks: '/networks',
    map: '/map',
    yandexAccounts: '/yandexAccounts',
    yandexMetrika: '/yandexMetrika',
    profileStatistic: '/profile-statistics',
    configPC: '/configs',
    communication: '/communication',
    locations: '/locations',
    dashboard: '/dashboard',
    niche: '/niche',
	niches: '/niches',
	pumping: '/pumping',
    profile: '/profile',
    management: '/management',
    projectsMob: '/manual-projects',
    appium: '/appium',
}